services:
  immichframe:
    build:
      context: ..
      target: dev
    ports:
      - 8080:8080
    env_file:
      - .env
    environment:
      TZ: "${TZ:-Etc/UTC}"
    volumes:
      - ./data/Config:/app/Config
      - ./data/App_Data:/app/App_Data
