services:
  immichframe:
    build:
      context: ..
      target: dev
    ports:
      - 8080:8080
    env_file:
      - .env
    environment:
      TZ: "${TZ:-Etc/UTC}"
    volumes:
      - C:\Users\mmart\Documents\Immichframe_data\Config:/app/Config
      - C:\Users\mmart\Documents\Immichframe_data\App_Data:/app/App_Data
