using ImmichFrame.Core.Interfaces;
using ImmichFrame.Core.Helpers;

namespace ImmichFrame.WebApi.Models;

public class ClientSettingsDto(IClientSettings settings) : IClientSettings
{
    public int Interval => settings.Interval;
    public double TransitionDuration => settings.TransitionDuration;
    public bool DownloadImages => settings.DownloadImages;
    public int RenewImagesDuration => settings.RenewImagesDuration;
    public bool ShowClock => settings.ShowClock;
    public bool ShowWeather => settings.ShowWeather;
    public bool ShowCalendar => settings.ShowCalendar;
    public bool ShowMetadata => settings.ShowMetadata;
    public string? ClockFormat => settings.ClockFormat;
    public string? ClockDateFormat => settings.ClockDateFormat;
    public bool ShowPhotoDate => settings.ShowPhotoDate;
    public bool ShowProgressBar => settings.ShowProgressBar;
    public string? PhotoDateFormat => settings.PhotoDateFormat;
    public bool ShowPhotoTimeAgo => settings.ShowPhotoTimeAgo;
    public bool ShowImageDesc => settings.ShowImageDesc;
    public bool ShowPeopleDesc => settings.ShowPeopleDesc;
    public bool ShowPeopleAge => settings.ShowPeopleAge;
    public bool ShowTagsDesc => settings.ShowTagsDesc;
    public bool ShowAlbumName => settings.ShowAlbumName;
    public bool ShowImageLocation => settings.ShowImageLocation;
    public string? ImageLocationFormat => settings.ImageLocationFormat;
    public string? PrimaryColor => settings.PrimaryColor;
    public string? SecondaryColor => settings.SecondaryColor;
    public string Style => settings.Style;
    public string? BaseFontSize => settings.BaseFontSize;
    public string? ClockFontSize => settings.ClockFontSize;
    public string? WeatherFontSize => settings.WeatherFontSize;
    public string? CalendarFontSize => settings.CalendarFontSize;
    public string? MetadataFontSize => settings.MetadataFontSize;
    public string? CalendarTimeZone => TimeZoneSettingsHelper.ResolveCalendarTimeZoneId(settings.CalendarTimeZone);
    public string? CalendarDateFormat => settings.CalendarDateFormat;
    public int CalendarLookaheadDays => CalendarSettingsLimits.NormalizeLookaheadDays(settings.CalendarLookaheadDays);
    public int CalendarMaxEvents => CalendarSettingsLimits.NormalizeMaxEvents(settings.CalendarMaxEvents);
    public string CalendarSortDirection => CalendarSettingsLimits.NormalizeSortDirection(settings.CalendarSortDirection);
    public string? ClockStyle => settings.ClockStyle;
    public string? WeatherStyle => settings.WeatherStyle;
    public string? CalendarStyle => settings.CalendarStyle;
    public string? MetadataStyle => settings.MetadataStyle;
    public string ClockPosition => settings.ClockPosition;
    public string WeatherPosition => settings.WeatherPosition;
    public string CalendarPosition => settings.CalendarPosition;
    public string MetadataPosition => settings.MetadataPosition;
    public List<string> WidgetStackOrder => settings.WidgetStackOrder.ToList();
    public bool ShowWeatherLocation => settings.ShowWeatherLocation;
    public bool ShowWeatherDescription => settings.ShowWeatherDescription;
    public string? WeatherIconUrl => settings.WeatherIconUrl;
    public bool ImageZoom => settings.ImageZoom;
    public bool ImagePan => settings.ImagePan;
    public bool ImageFill => settings.ImageFill;
    public bool PlayAudio => settings.PlayAudio;
    public string Layout => settings.Layout;
    public string Language => settings.Language;
}
